/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AutoDrjTest.java
 *
 * Created on Aug 17, 2015, 7:50:57 PM
 */

package test;

import gayakwad.DBConnection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class AutoDrjTest extends javax.swing.JDialog {

    Vector<String> data = new Vector<String>();
    /** Creates new form AutoDrjTest */
    public AutoDrjTest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try{
        DBConnection con = new DBConnection();
        ResultSet rs = con.executeQuery("select distinct(name) FROM raw_stock_mst r;");
        while(rs.next())
            data.add(rs.getString(1));
        }catch(Exception e){
            e.printStackTrace();;
        }
        //data.add("Maralkar");
        //data.add("Suraj");
        //data.add("Dhanaraj");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // suggeesion..
       
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
                 int caretPos = jTextField2.getCaretPosition();
                 String fullText = jTextField2.getText();

                String type = "";
                if(caretPos>1)
                    type = fullText.substring(0,caretPos);
                    jTextField2.setText(type);
                    return;
                }
        if(evt.getKeyChar()=='\n'){
            JOptionPane.showMessageDialog(rootPane, jTextField2.getText());
            return;
        }
            suggest();
    }//GEN-LAST:event_jTextField2KeyReleased

    private void suggest(){
         int caretPos = jTextField2.getCaretPosition();
        String fullText = jTextField2.getText();

        String type = "";
        if(caretPos>1)
            type = fullText.substring(0,caretPos);
        else{
            //jTextField2.setText(type);
            return;
        }

        //search type in data..
        String found = null;
        for(String str : data){
            if(str.toLowerCase().indexOf(type.toLowerCase())==0){
                found = str;
                break;
            }
        }
        if(found==null){
            jTextField2.setText(type);
            return;
        }
       // if(type.length()>=found.length())   return;
        String sugge = found.substring(type.length());
        jTextField2.setText(type+sugge);
        jTextField2.setSelectionStart((type+sugge).length());
        jTextField2.setSelectionEnd(type.length());
        jTextField2.moveCaretPosition(type.length());
        //jTextField2.selectAll();;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AutoDrjTest dialog = new AutoDrjTest(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
