/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Suggesion.java
 *
 * Created on Jul 27, 2015, 6:53:23 PM
 */

package test; 
import gayakwad.DBConnection;
import java.sql.ResultSet;
import java.util.*;
import javax.swing.KeyStroke;

/**
 *
 * @author admin
 */
public class Suggesion extends javax.swing.JDialog {


private static final String COMMIT_ACTION = "commit";

//String[] data;// = new String[] {"Dheeraj Maralk","abcd ttgg","xyz pqrs","mnop ddff"};
    /** Creates new form Suggesion */
    public Suggesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        final List<String> keywords = new ArrayList<String>();
        try{
            DBConnection con = new DBConnection();
            ResultSet rs = con.executeQuery("SELECT name FROM worker_mst w;");
            int i=0;
            while(i<3 && rs.next()){
                keywords.add( rs.getString(1));//.toLowerCase();
                i++;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        final String[] strs = new String[keywords.size()];
        for(int i=0;i<strs.length;i++)
            strs[i] = keywords.get(i);
        
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = strs;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

  //        keywords.add("autocomplete");
//        keywords.add("autocmmited");
//        keywords.add("stackabuse");
//        keywords.add("java");

        Autocomplete autoComplete = new Autocomplete(jTextField1, keywords);
        
        jTextField1.getDocument().addDocumentListener(autoComplete);
        jTextField1.getInputMap().put(KeyStroke.getKeyStroke("TAB"), COMMIT_ACTION);
        jTextField1.getActionMap().put(COMMIT_ACTION, autoComplete.new CommitAction());  
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Suggesion dialog = new Suggesion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
