/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Account.java
 *
 * Created on Jul 30, 2015, 2:41:23 PM
 */

package workers;

import ajgold.AJG_Static_AC;
import gayakwad.DBConnection;
import java.awt.Color;
import java.awt.Frame;
import java.sql.ResultSet;
import com.implidea.DecimalFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Account extends javax.swing.JDialog {
    DBConnection con = null;
    public static final int DEBIT = 0, CREDIT=1;
    DecimalFormat df = new DecimalFormat("#######.###");
    Frame parent;
    /** Creates new form Account */
    public Account(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
          java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(dim.width/2-this.getSize().width/2, 0);
        try{
        con = new DBConnection();
        }catch(Exception e){
            JOptionPane.showMessageDialog(parent, ""+e,"Error",JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }
        loadWNames();
    }


    private void loadWNames(){
        try{
            ResultSet rs = con.executeQuery("SELECT count(wid) FROM  worker_mst natural join worker_ac;");
            rs.next();
            int count = rs.getInt(1);
            WorkerObj[] wrks = new WorkerObj[count];
            rs = con.executeQuery("SELECT * FROM  worker_mst natural join worker_ac order by name;");
            int index = 0;
            while(rs.next()){
                int wid = rs.getInt(1);
                String name = rs.getString(2);
                String add = rs.getString(3);
                String contact = rs.getString(4);
                rs.getInt(5);   //raw suplier
                float gold_ac=rs.getFloat(6);
                float money_ac=rs.getFloat(7);
                float advacn=rs.getFloat(8);

                wrks[index] = new WorkerObj(name, add, contact, ""+wid);
                wrks[index].money_acc=money_ac;
                wrks[index].gold_acc=gold_ac;
                wrks[index].advance=advacn;
                index++;
              
            }
           jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(wrks));
           if(jComboBox2.getSelectedObjects().length>0)
           {
               jComboBox2.setSelectedIndex(0);
               jComboBox2ItemStateChanged(null);
            }else{
               JOptionPane.showMessageDialog(rootPane, "No Worker Entry!");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setText("Worker Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setText("Gold A/C");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Credit/Debit");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel5.setText("Cash A/C");

        jLabel6.setText("Credit/Debit");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel20.setText("Advance");

        jLabel21.setText("Credit/Debit");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Select");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Select");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jRadioButton1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jRadioButton2))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Convert Gold To Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Convert Money To Gold ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gold Rate:");

        jTextField2.setText("30000");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rs./10g");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gold:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cash:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Transation:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nave (Debit)", "Jama (Credit)" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox1KeyTyped(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("gm");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Weight");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tounch");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("%");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Rs.");

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("(Ctrl+T)");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Advance");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Rs.");

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel17))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jMenu1.setText("Options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Convert G To M
        String txt = jTextField2.getText();
        if(txt.length()<1){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Gold Rate!");
            return;
        }
        int selectedAc = -1;
        if(jRadioButton1.isSelected())
            selectedAc=1;
        if(jRadioButton2.isSelected())
            selectedAc=2;


        if(selectedAc==-1){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Money Account!");
            return;
        }

        float rate = 0;
        try{
        rate = Float.parseFloat(txt);
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Wrong Gold Rate Entry");
            return;
        }

       
        rate = rate/10; //per gm..
        WorkerObj wo = (WorkerObj) jComboBox2.getSelectedItem();

          EntryAmount ea = new EntryAmount(parent, true);
            ea.setAmount(Float.parseFloat(df.format((wo.gold_acc)/1000)));
            ea.setVisible(true);
            if(ea.amount==0){
                return;
            }
            if(Math.abs(ea.amount)>Math.abs(wo.gold_acc)){
                JOptionPane.showMessageDialog(parent, "Wrong Entry!");
                return;
            }


        float cost = rate*ea.amount;
        if(selectedAc==1)
            wo.money_acc+=cost;
        else
            wo.advance+=cost;

         try{
             if(selectedAc==1)
                con.executeUpdate("update worker_ac set money_ac="+wo.money_acc+" where wid="+wo.id);
             else
                 con.executeUpdate("update worker_ac set advance="+wo.advance+" where wid="+wo.id);

             wo.gold_acc=wo.gold_acc-(ea.amount*1000);
             con.executeUpdate("update worker_ac set gold_ac="+wo.gold_acc+" where wid="+wo.id);
             
             JOptionPane.showMessageDialog(rootPane, "Updated!", "Done!", JOptionPane.INFORMATION_MESSAGE);

                jComboBox2ItemStateChanged(null);
            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // wrke name itme st
        WorkerObj wo = (WorkerObj) jComboBox2.getSelectedItem();
        if(wo.gold_acc<0){
            float g = Math.abs(wo.gold_acc);
            
                jLabel4.setText(""+df.format(g/1000)+" gm");
                 jLabel4.setForeground(Color.red);
        }else{
            jLabel4.setText(""+df.format((wo.gold_acc)/1000)+" gm");
            jLabel4.setForeground(Color.black);
        }

        if(wo.money_acc<0){
            jLabel6.setForeground(Color.red);
            jLabel6.setText(""+Math.abs(wo.money_acc));
        }else{

            jLabel6.setForeground(Color.black);
            jLabel6.setText(""+Math.abs(wo.money_acc));
        }
        if(wo.advance<0){
            jLabel21.setForeground(Color.red);
        }else{
            jLabel21.setForeground(Color.black);
        }
        jLabel21.setText(""+Math.abs(wo.advance));
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // rs transction
        char key = evt.getKeyChar();
        if(key=='\n'){
            WorkerObj wo = ((WorkerObj) jComboBox2.getSelectedItem());
            String str = jTextField5.getText();
            if(str.length()<1){
                jTextField6.requestFocus();
                return;
            }
          
            
            int money=0;
            try{
                money = Integer.parseInt(str);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Wrong Entry Of Money","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String mess = "Confirm To ";
            if(jComboBox1.getSelectedIndex()==DEBIT)
                mess+="Debit(Nave) Rs. "+money+"?";
            else
                mess+="Credit(Jama) Rs. "+money+"?";
           int op = JOptionPane.showConfirmDialog(rootPane, mess);
           /*
            * 0-Yes
            * 1-No
            * 2-Cacle
            */
           if(op==0)
           {
               
           }else if(op==1){
               return;
           }else{
                return;
           }
           
           


            if(jComboBox1.getSelectedIndex()==DEBIT){
                wo.money_acc-=money;
               // aj_acc_money(-money);
            }else{
                wo.money_acc+=money;
               // aj_acc_money(money);
            }
            try{
                String qry = "";
                if(jComboBox1.getSelectedIndex()==DEBIT){
                    qry = "insert into aj_transations(name,tran_type,amount,dt,invoice_no,comment) values('"
                                            +wo.name+"','Money',-"+(money)+",now(),0,'Manural Debited(Nave)');";
                    con.executeUpdate(qry);
                    AJG_Static_AC.updateHand((money*(-1)), 0);
                }else{
                   qry = "insert into aj_transations(name,tran_type,amount,dt,invoice_no,comment) values('"
                                            +wo.name+"','MONEY',"+(money)+",now(),0,'Manual Credited (Jama)');";
                   con.executeUpdate(qry);
                   AJG_Static_AC.updateHand(money, 0);
                }
                
                con.executeUpdate("update worker_ac set money_ac="+wo.money_acc+" where wid="+wo.id);
                
                
                jComboBox2ItemStateChanged(null);
                JOptionPane.showMessageDialog(rootPane, "Updated!", "Done!", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jComboBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyTyped
        //  debit check key
          char key = evt.getKeyChar();
        if(key=='\n'){
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        //  wt key
         char key = evt.getKeyChar();
        if(key=='\n'){
            jTextField4.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // tnch key
         char key = evt.getKeyChar();
        if(key=='\n'){
            WorkerObj wo = ((WorkerObj) jComboBox2.getSelectedItem());
            if(jTextField3.getText().length()>0){
                if(jTextField4.getText().length()>0){
                    try{
                        float wt,tounch,fine;
                        try{
                            wt = Float.parseFloat(jTextField3.getText());
                            tounch = Float.parseFloat(jTextField4.getText());
                            fine = wt*(tounch/100);
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(rootPane, "Wrong Entry For Weight Or Tounch", "Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }

                        String mess = "Confirm To ";
                        if(jComboBox1.getSelectedIndex()==DEBIT)
                        {
                            mess+="Debit(Nave) Gold\n";
                        } else
                        {
                            mess += "Credit(Jama) Gold\n";
                        }
                        mess += "Wt: " + df.format(wt) + "gm\nTounch:" + tounch + "\nFine:" + df.format(fine) + "gm";
                       int op = JOptionPane.showConfirmDialog(rootPane, mess);
                       /*
                        * 0-Yes
                        * 1-No
                        * 2-Cacle
                        */
                       if(op==0)
                       {
                            if(jComboBox1.getSelectedIndex()==DEBIT)
                            {
                                wo.gold_acc-=(fine*1000);
                            } else
                            {
                                 wo.gold_acc+=(fine*1000); 
                            }
                       }else if(op==1){
                           return;
                       }else{
                            return;
                       }


                        String comment = "Manual Transaction Of Gold "+wt+" gm -> Tounch:"+tounch+"%";
                        String qry = "update worker_ac set gold_ac=("+wo.gold_acc+") where wid="+wo.id;
                        //System.out.println(qry);
                         con.executeUpdate(qry);
                         
                         //deduct/add ==> inhand..
                          if(jComboBox1.getSelectedIndex()==DEBIT){
                            qry = "insert into aj_transations(name,tran_type,amount,dt,invoice_no,comment) values('"
                                            +wo.name+"','GOLD',-"+(fine)+",now(),0,'"+comment+"');";
                            AJG_Static_AC.updateHand(0,(fine*(-1)));
                        }else{
                           qry = "insert into aj_transations(name,tran_type,amount,dt,invoice_no,comment) values('"
                                            +wo.name+"','GOLD',"+(fine)+",now(),0,'"+comment+"');";
                           AJG_Static_AC.updateHand(0,(fine));
                        }
                         con.executeUpdate(qry);


                         jComboBox2ItemStateChanged(null);
                         JOptionPane.showMessageDialog(rootPane, "Updated!", "Done!", JOptionPane.INFORMATION_MESSAGE);
                    }catch(Exception e){
                         JOptionPane.showMessageDialog(rootPane, "Wrong Entry For Weight Or Tounch", "Error", JOptionPane.ERROR_MESSAGE);
                         e.printStackTrace();;
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Tounch!");
                    return;
                }

            }
            else
                jTextField5.requestFocus();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jComboBox2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyTyped
        // w name key
        char key = evt.getKeyChar();
        if(key=='\n'){
            jComboBox2ItemStateChanged(null);
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox2KeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Exit
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // advance
         char key = evt.getKeyChar();
        if(key=='\n'){
            try {
                String txt= jTextField6.getText();
                if(txt.length()<1) {
                    jComboBox2.requestFocus();
                    return;
                }
                float adv = 0;
                try{
                    adv = Float.parseFloat(txt);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Wrong Entry For Advance");
                    return;
                }
                 


                    String mess = "Confirm To ";
                    if(jComboBox1.getSelectedIndex()==DEBIT)
                        mess+="Debit(Nave) Advance Rs. "+adv+"?";
                    else
                        mess+="Credit(Jama) Advance  Rs. "+adv+"?";
                   int op = JOptionPane.showConfirmDialog(rootPane, mess);
                   /*
                    * 0-Yes
                    * 1-No
                    * 2-Cacle
                    */
                   if(op==0)
                   {

                   }else if(op==1){
                       return;
                   }else{
                        return;
                   }





                 if(jComboBox1.getSelectedIndex()==DEBIT)
                     adv = (adv)*(-1);
                WorkerObj wo = ((WorkerObj) jComboBox2.getSelectedItem());
                con.executeUpdate("update worker_ac set advance=advance+"+adv+" where wid="+wo.id);

                //update transactions..

                String comment = "Advance Jama";
                if(adv<0)
                    comment = "Advance Nave";

                   String qry = "insert into aj_transations(name,tran_type,amount,dt,invoice_no,comment) values('"
                                            +wo.name+"','MONEY',"+(adv)+",now(),0,'"+comment+"');";
                   con.executeUpdate(qry);

                   AJG_Static_AC.updateHand(adv, 0);


                wo.advance += adv;
                JOptionPane.showMessageDialog(rootPane, "Advance Updated!");
                jComboBox2ItemStateChanged(null);
                jComboBox2.requestFocus();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Error:"+ex);
            }
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Convert M to G

         String txt = jTextField2.getText();
        if(txt.length()<1){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Gold Rate!");
            return;
        }
        int selectedAc = -1;
        if(jRadioButton1.isSelected())
            selectedAc=1;
        if(jRadioButton2.isSelected())
            selectedAc=2;

        if(selectedAc==-1){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Money Account!");
            return;
        }
        float rate = 0;
        try{
        rate = Float.parseFloat(txt);
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Wrong Gold Rate Entry");
            return;
        }

      
        

        rate = rate/10; //per gm..
        WorkerObj wo = (WorkerObj) jComboBox2.getSelectedItem();
        
        if(selectedAc==1)
        {
            EntryAmount ea = new EntryAmount(parent, true);
            ea.setAmount(wo.money_acc);
            ea.setVisible(true);
            if(ea.amount==0){
                return;
            }
            System.out.println("EA Amount:"+ea.amount);
            if(Math.abs(ea.amount)>Math.abs(wo.money_acc)){
                JOptionPane.showMessageDialog(parent, "Wrong Entry!");
                return;
            }
            float gold = wo.money_acc/rate;
            System.out.println("G Old:"+wo.gold_acc);
            gold*=1000;
            wo.gold_acc += gold;
            System.out.println("G New:"+wo.gold_acc);
            wo.money_acc=wo.money_acc-ea.amount;
        }
        else{
            EntryAmount ea = new EntryAmount(parent, true);
            ea.setAmount(wo.advance);
            ea.setVisible(true);
            if(ea.amount==0){
                return;
            }

            if(Math.abs(ea.amount)>Math.abs(wo.advance)){
                JOptionPane.showMessageDialog(parent, "Wrong Entry!");
                return;
            }
            float gold = ea.amount/rate;
            wo.gold_acc+=(gold*1000);
            wo.advance=wo.advance-ea.amount;
        }
         try{
             if(selectedAc==1)
                con.executeUpdate("update worker_ac set money_ac="+wo.money_acc+" where wid="+wo.id);
             else
                 con.executeUpdate("update worker_ac set advance="+wo.advance+" where wid="+wo.id);

             con.executeUpdate("update worker_ac set gold_ac="+wo.gold_acc+" where wid="+wo.id);
                 
             JOptionPane.showMessageDialog(rootPane, "Updated!", "Done!", JOptionPane.INFORMATION_MESSAGE);

                jComboBox2ItemStateChanged(null);
            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
            }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Account dialog = new Account(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    public static void aj_acc_money1(float money){
        try{
        DBConnection cnt = new DBConnection();
        cnt.executeUpdate("update money_mst set money=money+("+money+")");
        }catch(Exception e){
            e.printStackTrace();
        }
    }



    public static void aj_acc_credit_gold(float wt,float tounch){
        try{
            DBConnection cnt = new DBConnection();
            cnt.executeUpdate("insert into gold_mst(wt,tounch) values("+wt+","+tounch+")");
        }catch(Exception e){
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
