/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RawStock.java
 *
 * Created on Jul 27, 2015, 3:07:24 PM
 */

package workers;


import raw.*;
import gayakwad.DBConnection;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;



/**
 *
 * @author admin
 */
public class RawStockPickup extends javax.swing.JDialog {

    DBConnection con;
    Vector<RowItem> r_data ;

    /** Creates new form RawStock */
    public RawStockPickup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-getSize().height/2);

        //loadRow();
    }

    public void loadRow(String name,float wt){
        if(name.contains(" "))
            try{
                name = name.substring(0,name.indexOf(" "));
            }catch(Exception e){
                name="";
            }
        r_data = new Vector<RowItem>();
        try{
            con = new DBConnection();
            String qry = "SELECT * FROM raw_stock_mst where name like '%"+name+"%' and wt="+wt+" and qnty>0 order by name,wt;";
            System.out.println("Qry:"+qry);
            ResultSet rs = con.executeQuery(qry);
            while(rs.next()){
                RowItem ri = new RowItem(rs.getString(1), rs.getFloat(2),rs.getFloat(3));
                ri.qnty = rs.getInt(4);
                r_data.add(ri);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, ""+e, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        refreshTable();
        jTable1.requestFocus();
    }


    public void loadOutsourceMaterial(String oid){

        r_data = new Vector<RowItem>();
        try{
            con = new DBConnection();
            String qry = "SELECT itemName,wt,tounch FROM confermordermaterial where order_id="+oid;
            System.out.println("Qry:"+qry);
            ResultSet rs = con.executeQuery(qry);
            while(rs.next()){
                RowItem ri = new RowItem(rs.getString(1), rs.getFloat(2),rs.getFloat(3));
                ri.qnty = rs.getInt(4);
                r_data.add(ri);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, ""+e, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        refreshTable();
        jTable1.requestFocus();
    }

    public void loadAll(){
        
        r_data = new Vector<RowItem>();
        try{
            con = new DBConnection();
            String qry = "SELECT * FROM raw_stock_mst where qnty>0 order by name,wt;";
            System.out.println("Qry:"+qry);
            ResultSet rs = con.executeQuery(qry);
            while(rs.next()){
                RowItem ri = new RowItem(rs.getString(1), rs.getFloat(2),rs.getFloat(3));
                ri.qnty = rs.getInt(4);
                r_data.add(ri);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, ""+e, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        refreshTable();
        jTable1.requestFocus();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setText("Raw Stock");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Cancel ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12.10", "87.22", null},
                {"8.62", "98.11", null}
            },
            new String [] {
                "Name", "Tounch", "Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Select");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Options");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Finish Button
        dispose();;
}//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // jtable key
        char ch = evt.getKeyChar();
        try{
            int no = Integer.parseInt(""+ch);
            no--;
            jTable1.setRowSelectionInterval(no, no);
            jTable1.requestFocus();
        }catch(Exception e){
            System.out.println(e);
        }
}//GEN-LAST:event_jTable1KeyTyped

    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped
        // main panel key.
        char ch = evt.getKeyChar();
        try{
            int no = Integer.parseInt(""+ch);
            jTable1.setRowSelectionInterval(no, no);
            jTable1.requestFocus();
        }catch(Exception e){
            // System.out.println(e);
        }
    }//GEN-LAST:event_jPanel1KeyTyped

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Exit
        dispose();
}//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // select..
        int index = jTable1.getSelectedRow();
        if(index<0){
            JOptionPane.showMessageDialog(rootPane, "No Record Selected!");
            return;
        }
        TableModel tm = jTable1.getModel();
        selected_name = (String) tm.getValueAt(index, 0);
        selected_tnch = (String) tm.getValueAt(index, 1);
        selected_wt = (String) tm.getValueAt(index, 2);
        selected_qnty = (String) tm.getValueAt(index, 3);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        System.out.println("click count:"+evt.getClickCount());
    }//GEN-LAST:event_jTable1MousePressed

    String selected_name=null,selected_tnch=null,selected_wt=null,selected_qnty=null;


     private void debit1(){


        String text= JOptionPane.showInputDialog("Please Enter Quantity To Debit:");
        if(text!=null){
            try{
                int qnty = Integer.parseInt(text);

                if(qnty<1)  return;
                 int index = jTable1.getSelectedRow();
                if(index<0){
                    JOptionPane.showMessageDialog(rootPane, "Please Select A Record");
                    return;
                }
                RowItem ged = r_data.get(index);
                try {
                    String qry = "update raw_stock set qnty=qnty-"+qnty+" where name='"+ged.name+"'";
                    System.out.println(qry);
                    con.executeUpdate(qry);
                    JOptionPane.showMessageDialog(rootPane, "Material Debited!", "Done", JOptionPane.INFORMATION_MESSAGE);
                    //loadRow();
                } catch (Exception ex) {
                   JOptionPane.showMessageDialog(rootPane, ex, "Error", JOptionPane.ERROR_MESSAGE);
                   return;
                }

            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Wrong Entry!","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }


       
    }

     private void refreshTable(){
        String[][] data = new String[r_data.size()][];
        for(int i=0;i<data.length;i++)
        {
            data[i] = new String[4];
            RowItem ged = r_data.get(i);
            data[i][0] = ""+ged.name;
            data[i][1] = ""+ged.tounch;
            data[i][2] = ""+ged.wt;
            data[i][3] = ""+ged.qnty;
        }
        
         jTable1.setModel(new javax.swing.table.DefaultTableModel(data,   new String [] {
                "Name","Tounch","Weight","Quantity"
            }) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            boolean[] canEdit = new boolean [] {
                false, false,false,true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });


    }

     

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RawStockPickup dialog = new RawStockPickup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
