/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectCustomerDialog.java
 *
 * Created on Sep 3, 2018, 9:49:05 PM
 */

package org.ajgold.gst.dialogs;

import java.awt.Component;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.ajgold.gst.AllComns;
import sale.CustomerObj;

/**
 *
 * @author Dheeraj
 */
public class BankTransationDetails extends javax.swing.JDialog implements KeyListener {

    /** Creates new form SelectCustomerDialog */
    java.awt.Frame parent;
    public BankTransationDetails(java.awt.Frame parent, boolean modal,final Object[] list) {
        super(parent, modal);
        this.parent = parent;
        setUndecorated(true);
        setAlwaysOnTop(true);
        setResizable(false);
        initComponents();
        initTextFeild(txnType);
        initTextFeild(bankAccount);
        initTextFeild(amount);
        initTextFeild(goldConversion);
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    public void keyTyped(KeyEvent e) {}  public void keyPressed(KeyEvent e) {}

    public void keyReleased(KeyEvent e) {
        switch(e.getKeyCode()){
            case KeyEvent.VK_UP:
                ((JTextField) getPrevTabField((JTextField) e.getComponent())).requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                ((JTextField) getNextTabField((JTextField) e.getComponent())).requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                processSubmitAction(e.getComponent());
                break;
            default:
                break;
        }
    }

    private void processSubmitAction(Component t){
        if(t==txnType){
            isDialogOpen = true;
            SelectListDialog scd = new SelectListDialog(parent, true,new String[]{ "Bank RTGS", "Cheque" });
            scd.setVisible(true);
            txnType.setText(scd.getSelectedItem());
            isDialogOpen = false;
            focuseLost(txnType);
        }else if(t==bankAccount){
            isDialogOpen = true;
            SelectListDialog scd = new SelectListDialog(parent, true,new String[]{ "SBI 123456", "BoM 987654" });
            scd.setVisible(true);
            bankAccount.setText(scd.getSelectedItem());
            isDialogOpen = false;
            focuseLost(bankAccount);
        } else if(t==goldConversion){
            isDialogOpen = true;
            SelectListDialog scd = new SelectListDialog(parent, true,new String[]{ "Enable", "Disable" });
            scd.setVisible(true);
            goldConversion.setText(scd.getSelectedItem());
            isDialogOpen = false;
            focuseLost(goldConversion);
        }
    }


    private int getTabIndex(JTextField tf){
        for (int i = 0; i < tabIndex.size(); i++) {
            if(tf==(tabIndex.get(i)))  return i;
        }
        return -1;
    }

    private JComponent getTabField(int index){
        return tabIndex.get(index);
    }

    private JComponent getNextTabField(JTextField tf){
        int tI = (getTabIndex(tf)+1);
        if(tI>tabIndex.size()-1)    return null;
        return getTabField(tI);
    }

    private JComponent getPrevTabField(JTextField tf){
        int tI = (getTabIndex(tf));
        if(tI<1)    return null;
        return getTabField(tI-1);
    }

    private final ArrayList<JComponent> tabIndex = new ArrayList<JComponent>();
    
    private void initTextFeild(JTextField tf){
        tabIndex.add(tf);
        tf.addKeyListener(this);
        focuseLost(tf);
    }

    boolean isDialogOpen = false;
      private  void focused(JTextField jta){
        jta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jta.setBackground(new java.awt.Color(204, 204, 204));
    }

    private  void focuseLost(JTextField jta){
        jta.setBorder(null);
        jta.setBackground(new java.awt.Color(240, 240, 240));
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bankAccount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txnType = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        goldConversion = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Transaction Details:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Bank Account");

        bankAccount.setBackground(new java.awt.Color(240, 240, 240));
        bankAccount.setEditable(false);
        bankAccount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bankAccount.setText("Account for Transaction");
        bankAccount.setCaretColor(new java.awt.Color(240, 240, 240));
        bankAccount.setName("Bank Account"); // NOI18N
        bankAccount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankAccountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankAccountFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Amount (Rs.)");

        amount.setBackground(new java.awt.Color(240, 240, 240));
        amount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        amount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        amount.setName("Amount"); // NOI18N
        amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Transaction Type");

        txnType.setBackground(new java.awt.Color(240, 240, 240));
        txnType.setEditable(false);
        txnType.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txnType.setText("Select Transaction Type");
        txnType.setCaretColor(new java.awt.Color(240, 240, 240));
        txnType.setName("Transaction Type"); // NOI18N
        txnType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txnTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txnTypeFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Gold Conversion");

        goldConversion.setBackground(new java.awt.Color(240, 240, 240));
        goldConversion.setEditable(false);
        goldConversion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        goldConversion.setText("Select Transaction Type");
        goldConversion.setCaretColor(new java.awt.Color(240, 240, 240));
        goldConversion.setName("Gold Conversion"); // NOI18N
        goldConversion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                goldConversionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                goldConversionFocusLost(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(0, 0, 255));
        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Save");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Skip");
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(goldConversion, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(amount)
                                        .addComponent(bankAccount)
                                        .addComponent(txnType, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))))
                        .addContainerGap(151, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txnType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(bankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(goldConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankAccountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankAccountFocusGained
        // Customer Name Fouce Gained
        focused(bankAccount);
}//GEN-LAST:event_bankAccountFocusGained

    private void bankAccountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankAccountFocusLost
        // Customer Name Fouce lost
        if(!isDialogOpen)   focuseLost(bankAccount);
}//GEN-LAST:event_bankAccountFocusLost

    private void amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusGained
        focused(amount);
}//GEN-LAST:event_amountFocusGained

    private void amountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusLost
        focuseLost(amount);
}//GEN-LAST:event_amountFocusLost

    private void txnTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txnTypeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txnTypeFocusGained

    private void txnTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txnTypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txnTypeFocusLost

    private void goldConversionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goldConversionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_goldConversionFocusGained

    private void goldConversionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goldConversionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_goldConversionFocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        focused(bankAccount);
}//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        focuseLost(bankAccount);
}//GEN-LAST:event_jTextField5FocusLost

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        //YES

}//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        focused(txnType);
}//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        focuseLost(txnType);
}//GEN-LAST:event_jTextField6FocusLost

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        
}//GEN-LAST:event_jTextField6KeyReleased
 
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       if(AllComns.allCustomers==null){
                try {
                    AllComns.allCustomers = CustomerObj.loadAllAllCust();
                } catch (Exception ex) {
                   // JOptionPane.showMessageDialog(this,"Error While Loading Customer Data","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            BankTransationDetails scd = new BankTransationDetails(new Frame(), true,AllComns.allCustomers);
            scd.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField bankAccount;
    private javax.swing.JTextField goldConversion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txnType;
    // End of variables declaration//GEN-END:variables

}
