/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BarChart.java
 *
 * Created on Nov 5, 2014, 4:54:33 PM
 */

package workers.buffer;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author admin
 */
public class BarChart extends javax.swing.JPanel {

    /** Creates new form BarChart */
    Font fnt;
    public BarChart() {
        initComponents();
        fnt = new Font(Font.DIALOG, Font.BOLD, 24);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

 //   float max = 500;
     

    float buff=0;
    public void setBuff(float i){
       buff = i;

//       if(buff>max)
//           buff = max;

       repaint();
    }
    @Override
    public void paint(Graphics g){
       // super.paintAll(g);
        g.setColor(Color.black);
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.red);
        
        g.drawRect(5, 5, getWidth()-10, getHeight()-10);
        g.setColor(Color.blue);
     //   float newBuff = buff/max;
        g.setFont(fnt);
        if(buff>=0)
        {
            g.fillRect(10, 10, (int) (buff * (float) getWidth()) - 10, getHeight() - 20);
            g.setColor(Color.white);
            g.drawString(""+(int)(buff*100)+"%", getWidth()-55, 12+getHeight()/2);
        }
        else{
            g.setColor(Color.white);
            g.drawString("Not Available", 25, 12+getHeight()/2);
        }
        g.dispose();
      //  System.out.println((int)buff+":"+getWidth()+":"+(int) newBuff+":"+(int) ((newBuff)*(float)getWidth()));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    
}
