/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RowType.java
 *
 * Created on Jul 24, 2015, 8:00:34 AM
 */

package raw;

import gayakwad.Autocomplete;
import gayakwad.DBConnection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import com.implidea.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import workers.WorkerObj;

/**
 *
 * @author admin
 */
public class RowType extends javax.swing.JDialog {

        
    private  DBConnection con;
    private float totalLobor = 0.0f,totalFine=0.0f;

     Vector<String> data = new Vector<String>();
    DecimalFormat df = new DecimalFormat("#####.###");
    /** Creates new form RowType */
    public RowType(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //load supplier..
         try{
        con = new DBConnection();
        }catch(Exception e){
            JOptionPane.showMessageDialog(parent, ""+e,"Error",JOptionPane.ERROR_MESSAGE);
            dispose();
        }
        loadWNames();
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, 0);
        
         try{
            DBConnection con = new DBConnection();
            ResultSet rs = con.executeQuery("select distinct(name) FROM raw_stock_mst r;");
            while(rs.next())
                data.add(rs.getString(1));
        }catch(Exception e){
            e.printStackTrace();;
        }
         
         
    }

     private void loadWNames(){
        try{
            ResultSet rs = con.executeQuery("SELECT count(wid) FROM  worker_mst natural join worker_ac where raw_supplier=1; ");
            rs.next();
            int count = rs.getInt(1);
            WorkerObj[] wrks = new WorkerObj[count];
            rs = con.executeQuery("SELECT * FROM  worker_mst natural join worker_ac where raw_supplier=1;");
            int index = 0;
            while(rs.next()){
                int wid = rs.getInt(1);
                String name = rs.getString(2);
                String add = rs.getString(3);
                String contact = rs.getString(4);
                boolean raw_supplier = rs.getInt(5)==1;
                float gold_ac=rs.getFloat(6);
                float money_ac=rs.getFloat(7);

                wrks[index] = new WorkerObj(name, add, contact, ""+wid);
                wrks[index].money_acc=money_ac;
                wrks[index].gold_acc=gold_ac;
                index++;
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(wrks));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Finish (Ctrl+F)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Unit Weight", "Tounch", "Quantity", "Fine (g)", "Labor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Row Material Name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Unit Weight");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tounch");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Supplier");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox1KeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Labor");

        jTextField5.setText("0.0");
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Labor:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("0");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rs./unit");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("+");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Fine:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("0");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("+");

        jTextField6.setText("100");
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("=100");

        jTextField7.setText("0.2");
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, 190, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setText("Create New Row Meterial ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Finish");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Delete");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // wt key press
           char key = evt.getKeyChar();
            if(key=='\n')
             jTextField7.requestFocus();
       
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Finish Btn
        finish();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Finish Menu
        finish();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
 
        if(evt.getKeyChar()=='\n')
        {
          jTextField4.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // qntity key:
        if(evt.getKeyChar()=='\n')
        {
              jTextField6.requestFocus();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jComboBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyTyped
        // jchekc key
        
    }//GEN-LAST:event_jComboBox1KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // lobor
        
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Exit
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // qnty_extra
        char key = evt.getKeyChar();
            if(key=='\n')
             jTextField5.requestFocus();
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // Wasteg
        char key = evt.getKeyChar();
            if(key=='\n')
             jTextField3.requestFocus();
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // suggesion
         if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
                 int caretPos = jTextField2.getCaretPosition();
                 String fullText = jTextField2.getText();

                String type = "";
                if(caretPos>1)
                    type = fullText.substring(0,caretPos);
                    jTextField2.setText(type);
                    return;
                }
        if(evt.getKeyChar()=='\n'){
            //JOptionPane.showMessageDialog(rootPane, jTextField2.getText());
            jTextField2.requestFocus();
            return;
        }
            suggest();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        // 
         if(evt.getKeyChar()=='\n')
        {
              jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // labor
        
        if(evt.getKeyChar()=='\n')
        {
            addToTable();
            reset();
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Delete menu..
        int index = jTable1.getSelectedRow();
        if(index<0){
            JOptionPane.showMessageDialog(rootPane, "Please Select Record To Delete!");
            return;
        }
        rowItems.remove(index);
           refreshTable();
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    
    private void suggest(){
         int caretPos = jTextField1.getCaretPosition();
        String fullText = jTextField1.getText();

        String type = "";
        if(caretPos>1)
            type = fullText.substring(0,caretPos);
        else{
            //jTextField2.setText(type);
            return;
        }

        //search type in data..
        String found = null;
        for(String str : data){
            if(str.toLowerCase().indexOf(type.toLowerCase())==0){
                found = str;
                break;
            }
        }
        if(found==null){
            jTextField1.setText(type);
            return;
        }
       // if(type.length()>=found.length())   return;
        String sugge = found.substring(type.length());
        jTextField1.setText(type+sugge);
        jTextField1.setSelectionStart((type+sugge).length());
        jTextField1.setSelectionEnd(type.length());
        jTextField1.moveCaretPosition(type.length());
        //jTextField2.selectAll();;
    }
    
    private void finish(){
        try {
            DBConnection con = new DBConnection();
            
            for(RowItem ri : rowItems){
                //check exists..
                String check_q = "SELECT qnty,rec_id FROM raw_stock_mst where name='"+ri.name+"' and wt="+ri.wt+" and tounch="+ri.tounch+";";
                System.out.println(check_q);
                ResultSet rs_chk = con.executeQuery(check_q);
                if(rs_chk.next()){
                    //update
                    int qnty = rs_chk.getInt(1);
                    int rec_id = rs_chk.getInt(2);
                    int newQnty = qnty+ri.qnty;
                    con.executeUpdate("update raw_stock_mst set qnty="+newQnty+"  where rec_id="+rec_id);
                }else
                 {
                     int nextRec = 0;
                    ResultSet rs = con.executeQuery("select max(rec_id) from raw_stock_mst");
                    try{
                        rs.next();
                        nextRec =rs.getInt(1);
                    }catch(Exception e){}
                    nextRec++;
                    String qry = "insert into raw_stock_mst values('"
                                    +ri.name+"',"+ri.wt+","+ri.tounch+","
                                    +ri.qnty+","+ri.wid+","+nextRec+","
                                    +ri.wastage+","+ri.qnty_diff+","+ri.labor+");";
                    con.executeUpdate(qry);
                }



                //Add to faulty..
                String fQty = "SELECT qnty,rid FROM faultyraw where name='"+ri.name+"' and wt="+ri.wt+" and tounch="+ri.tounch+";";
                ResultSet fRs = con.createStatement().executeQuery(fQty);
                if(fRs.next()){
                    int qnty = fRs.getInt(1);
                    int rid = fRs.getInt(2);
                    int newQnty = ri.qnty_diff+qnty;
                    con.executeUpdate("update faultyraw set qnty="+newQnty+" where rid = "+rid);
                }else{
                    con.executeUpdate("insert into faultyraw(name,tounch,wt,qnty) values('"+ri.name+"',"+ri.tounch+","+ri.wt+","+ri.qnty_diff+")");
                }
            }
            //update workers a/c
            WorkerObj wo = (WorkerObj) jComboBox1.getSelectedItem();
            wo.gold_acc+=(totalFine);
            wo.money_acc+=(totalLobor);
            con.executeUpdate("update worker_ac set gold_ac="+wo.gold_acc+", money_ac="+wo.money_acc+" where wid="+wo.id);

            //System.out.println(qry);
            JOptionPane.showMessageDialog(rootPane, "Raw Material Updated!", "Done", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
           JOptionPane.showMessageDialog(rootPane, ""+ex, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    private void reset(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField1.requestFocus();
    }
    

    Vector<RowItem> rowItems = new Vector<RowItem>();

    private void addToTable(){
        String name = jTextField1.getText();
        String wt  = jTextField2.getText();
        String tnch  = jTextField3.getText();
        String qntyS  = jTextField4.getText();
        String lbrS  = jTextField5.getText();
        String wasteg_txt=jTextField7.getText();
        String qnty_extra_txt =jTextField6.getText();

        


        float wttt = -1,tounch=-1,labor=0.0f,wasteg=0;
        int qnty=0,qnty_extra;
        try{
            wttt = Float.parseFloat(wt);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error", "Wrong Unit Weigth Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }


        try{
            wasteg = Float.parseFloat(wasteg_txt);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error", "Wrong Unit Weigth Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

         try{
            tounch = Float.parseFloat(tnch);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error", "Wrong Tounch Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

         try{
            qnty = Integer.parseInt(qntyS);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error", "Wrong Quantity Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }

          try{
            qnty_extra = Integer.parseInt(qnty_extra_txt);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error", "Wrong Quantity Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }




         try{
            labor = Float.parseFloat(lbrS);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error", "Wrong Quantity Entry", JOptionPane.ERROR_MESSAGE);
            return;
        }
        RowItem ri = new RowItem(name, wttt,tounch);
        ri.qnty=qnty;
        ri.qnty_diff=qnty_extra;
        ri.wastage=wasteg;
        ri.labor=labor;
        ri.wid = ((WorkerObj) jComboBox1.getSelectedItem()).id;
        rowItems.add(ri);
        int finalQnty = qnty+qnty_extra;
        totalLobor+= (finalQnty*labor);
        totalFine+= (finalQnty*(wttt+wasteg))*(tounch/100);

        jLabel9.setText(""+df.format(totalLobor));
        if(totalFine<10000) //10g
            jLabel13.setText(""+df.format(totalFine));
        else
            jLabel13.setText(""+df.format(totalFine/1000.0f)+" g");
        refreshTable();
    }

    private void refreshTable(){
        String[][] data = new String[rowItems.size()][];
        for(int i=0;i<data.length;i++)
        {
            RowItem ri = rowItems.get(i);
            data[i] = new String[6];
            data[i][0] = ri.name;
            data[i][1] = ""+ri.wt+"+"+ri.wastage;
            data[i][2] = ""+ri.tounch;
            data[i][3] = ""+ri.qnty+"+"+ri.qnty_diff;
            data[i][4]=""+df.format((((ri.qnty+ri.qnty_diff)*(ri.wt+ri.wastage))*(ri.tounch/100))/1000);
            data[i][5] = ""+(ri.labor*(ri.qnty+ri.qnty_diff));            
        }
          jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
            new String [] {
                "Name", "Unit Weight", "Tounch", "Quantity", "Fine (g)", "Labor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RowType dialog = new RowType(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
